### ISSUE TITLE
CI fails to verify build of PR against release branch

### ISSUE THREAD

**Issue by dvrogozh** [Intel-Media-SDK/product-configs#120]
PR: https://github.com/Intel-Media-SDK/MediaSDK/pull/1164
Build fails: http://mediasdk.intel.com/buildbot/#builders/17/builds/583

Looks to be some triggerring/checkout issue.

**Comment by azhogov** [comment]
It is due to manipulation with history in Git... Just don't change it (until finishing builds at least...)

**Comment by azhogov** [comment]
It is fixed now
