### ISSUE TITLE
Disable/bypass some CI checks for one of the path in media-driver

### ISSUE THREAD

**Issue by dvrogozh** [Intel-Media-SDK/product-configs#225]
Hi,

See this CI build failure: https://github.com/intel/media-driver/pull/731

Please, be aware that this path in media-driver https://github.com/intel/media-driver/blob/master/media_driver/linux/common/os/i915/include/uapi is managed by _strict_ rules described in https://github.com/intel/media-driver/blob/master/media_driver/linux/common/os/i915/include/uapi/README. No changes to the code will be made to satisfy artificial CI requirements such as licence checks, copyrights check, etc. The code is copied from the Linux kernel upstream as-is strictly without modifications. This is critical.

Could you, please, adjust CI verification in media driver to bypass such checks and focus entirely on code buildability. 

@XinfengZhang: FYI

Regards,
Dmitry.

**Comment by eponomar** [comment]
Need to rebase changeset in PR to enable the fix
