### ISSUE TITLE
18.4: Android build fails due to checkout

### ISSUE THREAD

**Issue by dvrogozh** [Intel-Media-SDK/product-configs#93]
Branch: https://github.com/Intel-Media-SDK/MediaSDK/commits/intel-mediasdk-18.4
Commit: https://github.com/Intel-Media-SDK/MediaSDK/commit/7d35bc514df86e661e3b8db26ca449c8e32b41bc
See: http://bb.msdk.intel.com/private/#/builders/1/builds/1800

Android build fails. Please, fix.

**Comment by azhogov** [comment]
fixed
